[fold] Better handling of 'null' result in json config

diff --git a/packages/2/user/ubuntu_hooks b/packages/2/user/ubuntu_hooks
--- a/packages/2/user/ubuntu_hooks
+++ b/packages/2/user/ubuntu_hooks
@@ -12,9 +12,10 @@ function user_image_name(){
         exit 1
     fi
 
-    local name=$(cat ${options_file} | jq -r ".name?")
-    if [[ -z ${name} || ${name} = null ]]; then
-        echo "Error: Json file ${options_file} does not specify a name."
+    local name
+    name="$(jq -r '.name? // empty' ${options_file})"
+    if [[ -z ${name} ]]; then
+        echo "Error: Json file ${options_file} does not specify a name." >&2
         exit 1
     fi
 
@@ -38,9 +39,11 @@ function create_user() {
     local tmp_dockerfile=$(mktemp "${this_dir}/dockerfile.XXXXXXXXXXXX")
     dockerfile_from_template ${this_dir}/ubuntu_dockerfile_template ${options_file} ${tmp_dockerfile}
 
+    local image_name
+    image_name=$(user_image_name)
     docker build \
            $(extra_docker_flags create ${options_file}) \
-           -t $(user_image_name) \
+           -t ${image_name} \
            -f ${tmp_dockerfile} \
            ${proj_dir}
 
@@ -62,15 +65,17 @@ function create_user() {
 
      local name="user_dev_env${RANDOM}"
      local to_run
-     if [[ -z $(jq '.cmd?' "${options_file}") ]]; then
+     if [[ -z $(jq '.cmd? // empty' "${options_file}") ]]; then
         # only run a shell on containers without a default cmd
-        local to_run=${SHELL}
+        to_run=${SHELL}
      fi
 
+     local image_name
+     image_name=$(user_image_name)
      docker run -it \
             $(extra_docker_flags run ${options_file}) \
             --name ${name} \
             --rm \
-            $(user_image_name) \
+            ${image_name} \
             ${to_run}
  }
