[fold] Add support for attach command

diff --git a/packages/2/user/ubuntu_hooks b/packages/2/user/ubuntu_hooks
--- a/packages/2/user/ubuntu_hooks
+++ b/packages/2/user/ubuntu_hooks
@@ -79,3 +79,43 @@ function create_user() {
             ${image_name} \
             ${to_run}
  }
+
+ function attach_user(){
+     if [[ -z ${options_file} ]]; then
+         echo "Error: must specify an options file in ${FUNCNAME[0]}." >&2
+         exit 1
+     fi
+
+     if [[ $# -gt 1 ]]; then
+         echo "Error: Too many arguments to ${FUNCNAME[0]}. All arguments excpet command to run must come from an options file." >&2
+         usage
+         exit 1
+     fi
+
+     to_run=${SHELL}
+     if [[ $# -eq 1 ]]; then
+         to_run="${1}"
+     fi
+
+     local image_name
+     image_name=$(user_image_name)
+     # check for existing running container using the image
+     local container_name
+     container_name=$(docker ps --filter ancestor="${image_name}" -q)
+     if [[ -n ${container_name} ]]; then
+         docker exec -it "${container_name}" "${to_run}"
+     else
+         # start a new container
+         local name="user_dev_env${RANDOM}"
+
+         tmp_json=$(mktemp "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")
+         jq 'del(.detached)' ${options_file} > ${tmp_json}
+         docker run -it \
+                $(extra_docker_flags run ${tmp_json}) \
+                --name ${name} \
+                --rm \
+                ${image_name} \
+                "${to_run}"
+         rm ${tmp_json}
+     fi
+ }
diff --git a/scripts/defcon b/scripts/defcon
--- a/scripts/defcon
+++ b/scripts/defcon
@@ -12,6 +12,8 @@ UBUNTU_VERSION=18.04
 scripts_dir=$(realpath $(dirname "${BASH_SOURCE[0]}"))
 proj_dir=$(realpath "${scripts_dir}/..")
 packages_dir=$(realpath "${scripts_dir}/../packages")
+
+# json file containing defcon options for controling docker containers
 options_file=""
 
 ################################################################################
@@ -377,7 +379,7 @@ function load_package_versions () {
 
 ################################################################################
 
-valid_commands=(create run push)
+valid_commands=(create run push attach)
 valid_components=(gcc rippled_dev_base base rippled-dev user-dev rippled-deploy rippled-dogfood)
 
 function usage(){
@@ -567,6 +569,26 @@ run_command() {
     fi
 }
 
+attach_command() {
+    if [[ $# -lt 1 ]]; then
+        echo "Must specify component to attach: ${*}." >&2
+        exit 1
+    fi
+
+    local component=${1}; shift
+    if is_valid_package ${component}; then
+        source_package_hooks ${component}
+        attach_${component} "${@}"
+    elif is_valid_package_priority ${component}; then
+        echo "Error: the attach command does not support running all packages at a given priority" >&2
+        exit 1
+    else
+        echo "Invalid component: ${component}" >&2
+        usage
+        exit 1
+    fi
+}
+
 case ${command} in
     create)
         create_command ${component} "${@}"
@@ -574,6 +596,10 @@ case ${command} in
         ;;
     run)
         run_command ${component} "${@}"
+        exit 0
+        ;;
+    attach)
+        attach_command ${component} "${@}"
         exit 0
         ;;
     push)
