[fold] Support for core files

diff --git a/scripts/defcon b/scripts/defcon
--- a/scripts/defcon
+++ b/scripts/defcon
@@ -420,7 +420,9 @@ while getopts ":f:" opt; do
             shift;shift
             ;;
         \?)
-            echo "Invalid option: -$OPTARG"
+            echo "Invalid option: -$OPTARG" >&2
+            exit 1
+            ;;
     esac
 done
 
